version: '2'

services:
  app:
    #build: .
    image: patt1293/cambae-backend-api:1.4
    #volumes:
    #  - ./:/usr/src/app
    ports:
      - 6901
    depends_on:
      - db
    environment:
      ENV: local
      SECRET_KEY: eEnbvGyk]Y8R/BgU
      SQLALCHEMY_DATABASE_URI_TEST: 'postgresql+psycopg2://tester:12345@db/flaskdb_test'
      FLASK_APP: autoapp.py
      FLASK_DEBUG: 1

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/data/db
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: tester
      POSTGRES_DB: flaskdb

volumes:
  db-data:
