version: '2'
services:
  pineappleslutbabe:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "pineappleslutbabe"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  nami3neko:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "nami3neko"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  sexbunny180:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "sexbunny180"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  annyamarie:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "annyamarie"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  favourite-drink:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "favourite_drink"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  xxxstripdancer:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "xxxstripdancer"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  skyewatson:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "skyewatson"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  moonbaby11:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "moonbaby11"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  aubrilee:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "aubrilee"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  blueasfuck:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "blueasfuck"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  xxlittlesisxx:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "xxlittlesisxx"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  lilimariexx:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "lilimariexx"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  dawnwillow:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "dawnwillow"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  cherrycrush:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "cherrycrush"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  dakota-britto:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "dakota_britto"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  pussykitten3434:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "pussykitten3434"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  ariel-vaughn:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "ariel_vaughn"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  nymphono:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "nymphono"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  peachescake:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "peachescake"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"
  hi-cut-cutie:
  image: patt1293/chaturbae-client:latest
  environment:
    CB_USERNAME: "hi_cut_cutie"
    AWSKEY: "${AWSKEY}"
    AWSSECRET: "${AWSSECRET}"
    SERVICE_IP: "172.26.5.97"
    DEBUG: "chaturbae:*"