version: '2'
services:
  elk:
    labels:
      io.rancher.scheduler.affinity:host_label: service=elk
    image: patt1293/elk:${RELEASE}
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5045:5045"
      - "12201:12201/udp"
      - "12202:12202"
      - "12202:12202/udp"
    volumes:
      - /home/elasticsearch:/var/lib/elasticsearch
