version: '2'
services:
  api:
    image: patt1293/open-nsfw:${RELEASE}
    environment:
      PORT: '5000'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
