version: '2'
services:
  emilypreponxo:
      #image: ''
      build: .
      labels:
        app: myfreebae:client
        io.rancher.container.hostname_override: container_name
        io.rancher.container.pull_image: always
        io.rancher.scheduler.affinity:host_label: service=client
      environment:
        MODELNAME: "EmilyPreponXO"
        BACKEND: "elk.backend.chaturbae.tv"
        SYSLOG_TAG: '{docker: "myfreebae-client"}'
        LOGSTASH_FIELDS: "platform=docker,job=myfreebae-client,model_username=EmilyPreponXO"
        DECODE_JSON_LOGS: "true"
        DEBUG: "myfreebae:*"
      volumes:
        - '.:/usr/src/app'
