stage ('Git Clone latest repo') {
  node{
    deleteDir()
    dir('clients/myfreebae'){
    withCredentials([file(credentialsId: 'env', variable: 'envi')]) {
       sh "cp \"\$envi\" .env"
       sh "cat \"\$envi\""
     }
    }
    git url: 'https://github.com/patrick-hudson/cambae.git'

  }
}
stage ('Build Docker Image') {
  node{
      dir('clients/myfreebae'){
      container = docker.build('patt1293/myfreebae', ".")
      }
  }
}
stage ("Push Docker Image") {
  node{
      dir('clients/myfreebae'){
      buildDate = sh(returnStdout: true, script: 'date -u +"%FT%H%MZ"').trim()
      docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
          container.push("build-${env.BUILD_NUMBER} ")
          container.push('latest')
      }
    }
  }
}
