version: '2'
services:
  haproxy:
    labels:
      io.rancher.scheduler.affinity:host_label: service=watcher
    ports:
    - 5000
    - 8081
    - 6901
    - 6902
    image: rancher/lb-service-haproxy:latest
