stage ('Git Clone latest repo') {
  node{
    deleteDir()
    git url: 'https://github.com/patrick-hudson/cambae.git'

  }
}
stage ('Deploy Backend Load Balancer') {
  node{
      dir('services/backend-loadbalancer'){
      sh "export RELEASE=build-${env.BUILD_NUMBER} && rancher up -s backend-loadbalancer -u -d -c --force-recreate"
      }
  }
}
