version: '2'
services:
  haproxy:
    lb_config:
      config: |-
          global
              maxconn 4096
              maxpipes 1024
          defaults
              timeout client 36000s
              timeout server 36000s
      port_rules:
      - source_port: 5000
        target_port: 5000
        service: open-nsfw/api
      - source_port: 6902
        target_port: 6902
        service: backend-api-node/api
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
