version: '2'
services:
  elk:
    labels:
      io.rancher.scheduler.affinity:host_label: service=elk
    image: patt1293/elk-docker
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5045:5045"
      - "12201:12201/udp"
      - "12202:12202"
      - "12202:12202/udp"
    volumes:
      - /home/elasticsearch:/var/lib/elasticsearch

  app:
    labels:
      io.rancher.scheduler.affinity:host_label: service=elk
    image: patt1293/cambae-backend-api:latest
    #volumes:
    #  - ./:/usr/src/app
    ports:
      - 6901
    depends_on:
      - db
    environment:
      ENV: local
      SECRET_KEY: eEnbvGyk]Y8R/BgU
      SQLALCHEMY_DATABASE_URI_TEST: 'postgresql+psycopg2://tester:12345@db/flaskdb_test'
      FLASK_APP: autoapp.py
      FLASK_DEBUG: 1

  db:
    labels:
      io.rancher.scheduler.affinity:host_label: service=elk
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/data/db
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: tester
      POSTGRES_DB: flaskdb

volumes:
  db-data:
