version: '2'
services:
  irc-nsfw-api-lb:
    scale: 3
    lb_config:
      port_rules:
      - source_port: 5000
        target_port: 5000
        service: chaturbae-irc-nudeapi/nsfw-api
      - source_port: 8081
        target_port: 8081
        service: chaturbae-irc-nudeapi/irc-worker
      - source_port: 6901
        target_port: 6901
        service: chaturbae-irc-nudeapi/app
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
