stage ('Git Clone latest repo') {
  node{
    deleteDir()
    dir('services/logspout'){
    withCredentials([file(credentialsId: 'env', variable: 'envi')]) {
       sh "cp \"\$envi\" .env"
       sh "cat \"\$envi\""
     }
    }
    git url: 'https://github.com/patrick-hudson/cambae.git'

  }
}
stage ('Build Docker Image') {
  node{
      dir('services/logspout'){
      container = docker.build('patt1293/logspout', ".")
      }
  }
}
stage ("Push Docker Image") {
  node{
      dir('services/logspout'){
      buildDate = sh(returnStdout: true, script: 'date -u +"%FT%H%MZ"').trim()
      docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
          container.push("build-${env.BUILD_NUMBER} ")
          container.push('latest')
      }
    }
  }
}
stage ('Deploy Docker Image') {
  node{
      dir('services/logspout'){
      sh "export RELEASE=build-${env.BUILD_NUMBER} && rancher up -s logspout -u -d -c --force-recreate"
      }
  }
}
