version: '2'
services:
  irc_worker:
    image: patt1293/chaturbae-irc
  nsfw_api:
    image: eugencepoi/nsfw_api
    environment:
      PORT: "5000"
    ports:
      - "5000:5000"
networks:
  default:
    external:
      name: frontend
