version: '2'
services:
  irc-worker:
    image: patt1293/chaturbae-irc
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    ports:
      - "8081"
  nsfw-api:
    image: patt1293/nsfw_api
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    environment:
      PORT: "5000"
    ports:
      - "5000"
