apiVersion: apps/v1beta2
kind: Deployment
metadata:
  creationTimestamp: null
  name: cambae-backend-api-node
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: cambae-backend-api-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cambae-backend-api-node
    spec:
      containers:
      - env:
        - name: SENDGRID_KEY
          value: '1234'
        - name: MASTER_KEY
          value: kQe5bv7doIgLauIgL1DmnPeGr7cd5iS9
        - name: JWT_SECRET
          value: q478FRlq1Dy37JjcO3ZWL9v3lzUllBIg
        image: patt1293/cambae-backend-api-node:build-32
        imagePullPolicy: Always
        name: cambae-backend-api-node
        ports:
        - containerPort: 6902
          name: 6902tcp01
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: mongo
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Always
        name: mongo
        ports:
        - containerPort: 27017
          name: 127017tcp01
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  creationTimestamp: null
  name: open-nsfw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: open-nsfw
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: open-nsfw
    spec:
      containers:
      - env:
        - name: 'PORT'
          value: '5000'
        image: patt1293/open-nsfw:build-21
        imagePullPolicy: Always
        name: open-nsfw
        ports:
        - containerPort: 5000
          name: 5000tcp01
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
