version: '2'
services:
  api:
      image: 'patt1293/cambae-backend-api-node:${RELEASE}'
      #build: .
      depends_on:
        - 'mongodb'
      restart: always
      labels:
        io.rancher.scheduler.affinity:host_label: service=watcher
      #abels:
      #  app: myfreebae:client
      #  io.rancher.container.hostname_override: container_name
      #  io.rancher.container.pull_image: always
      environment:
        SENDGRID_KEY: 1234
        MASTER_KEY: kQe5bv7doIgLauIgL1DmnPeGr7cd5iS9
        JWT_SECRET: q478FRlq1Dy37JjcO3ZWL9v3lzUllBIg
  mongodb:
    image: 'mongo'
    labels:
      io.rancher.scheduler.affinity:host_label: has_elk=true
    ports:
      - "27017:27017"
    volumes:
      - /Users/patrick/Documents/mongodb/data:/data/db

      #volumes:
      #  - '.:/usr/src/app'
