stage ('Git Clone latest repo') {
  node{
    deleteDir()
    git url: 'https://github.com/patrick-hudson/cambae.git'

  }
}
stage ('Build Docker Image') {
  node{
      dir('services/cambae-backend-api-node'){
      container = docker.build('patt1293/cambae-backend-api-node', ".")
      }
  }
}
stage ("Push Docker Image") {
  node{
      dir('myfreebae'){
      buildDate = sh(returnStdout: true, script: 'date -u +"%FT%H%MZ"').trim()
      docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
          container.push("build-${env.BUILD_NUMBER} ")
          container.push('latest')
      }
    }
  }
}
